"use strict";

/**
 * Builds the Navis TV APK.
 *
 * Wraps Gradle so that `npm run build:android` works the same way as the web
 * build: it locates the Android SDK and a compatible JDK, then copies the
 * resulting APK next to the other distributable artifacts in bin/.
 */

const fs = require("fs");
const os = require("os");
const path = require("path");
const { spawnSync } = require("child_process");

const projectRoot = path.resolve(__dirname, "..");
const androidDir = path.join(projectRoot, "android");
const outputDir = path.join(projectRoot, "bin");

const isDebug = process.argv.includes("--debug");
const variant = isDebug ? "debug" : "release";
const gradleTask = isDebug ? ":app:assembleDebug" : ":app:assembleRelease";

// Gradle 8.9 runs on JDK 17 to 22. Newer JDKs (24, 25...) are rejected by
// Gradle itself, with an error that is hard to act on, so we check up front.
const MIN_JDK = 17;
const MAX_JDK = 22;

const fail = (message) => {
  console.error(`\n[build:android] ${message}\n`);
  process.exit(1);
};

const findAndroidSdk = () => {
  const candidates = [
    process.env.ANDROID_HOME,
    process.env.ANDROID_SDK_ROOT,
    path.join(os.homedir(), "Library", "Android", "sdk"),
    path.join(os.homedir(), "Android", "Sdk"),
    "/usr/local/lib/android/sdk",
  ].filter(Boolean);

  return candidates.find((dir) => fs.existsSync(path.join(dir, "platforms")));
};

const jdkMajor = (javaHome) => {
  const javaBin = path.join(javaHome, "bin", "java");
  if (!fs.existsSync(javaBin)) return null;
  // `java -version` writes to stderr, so both streams have to be inspected.
  const result = spawnSync(javaBin, ["-version"], { encoding: "utf-8" });
  const output = `${result.stdout || ""}${result.stderr || ""}`;
  const match = /version "(\d+)/.exec(output);
  return match ? parseInt(match[1], 10) : null;
};

const isSupportedJdk = (major) =>
  major !== null && major >= MIN_JDK && major <= MAX_JDK;

const findJavaHome = () => {
  const explicit = process.env.NAVIS_ANDROID_JAVA_HOME || process.env.JAVA_HOME;
  if (explicit && isSupportedJdk(jdkMajor(explicit))) {
    return explicit;
  }

  // macOS keeps every installed JDK registered with java_home.
  if (process.platform === "darwin") {
    for (let version = MAX_JDK; version >= MIN_JDK; version--) {
      const result = spawnSync("/usr/libexec/java_home", ["-v", String(version)], {
        encoding: "utf-8",
      });
      if (result.status === 0) {
        const home = result.stdout.trim();
        if (isSupportedJdk(jdkMajor(home))) return home;
      }
    }
  }

  const linuxJvmDir = "/usr/lib/jvm";
  if (fs.existsSync(linuxJvmDir)) {
    const found = fs
      .readdirSync(linuxJvmDir)
      .map((entry) => path.join(linuxJvmDir, entry))
      .find((home) => isSupportedJdk(jdkMajor(home)));
    if (found) return found;
  }

  return null;
};

const sdkDir = findAndroidSdk();
if (!sdkDir) {
  fail(
    "Android SDK not found. Install it (Android Studio, or `brew install --cask android-commandlinetools`)\n" +
      "then set ANDROID_HOME to its location."
  );
}

const javaHome = findJavaHome();
if (!javaHome) {
  const current = process.env.JAVA_HOME ? jdkMajor(process.env.JAVA_HOME) : null;
  fail(
    `No JDK between ${MIN_JDK} and ${MAX_JDK} found` +
      (current ? ` (JAVA_HOME points to JDK ${current}, which Gradle rejects)` : "") +
      ".\nInstall one, for example `brew install --cask temurin@21`, or set\n" +
      "NAVIS_ANDROID_JAVA_HOME to an existing JDK 17-21 install."
  );
}

// Gradle reads the SDK location from local.properties. It is machine specific
// and gitignored, so it is (re)generated on every build.
fs.writeFileSync(
  path.join(androidDir, "local.properties"),
  `# Generated by scripts/build-android.js -- do not commit.\nsdk.dir=${sdkDir}\n`
);

console.log(`[build:android] variant     : ${variant}`);
console.log(`[build:android] android sdk : ${sdkDir}`);
console.log(`[build:android] jdk         : ${javaHome} (${jdkMajor(javaHome)})`);
console.log(
  `[build:android] server      : ${
    process.env.NAVIS_TV_SERVER_URL || "default from android/app/build.gradle"
  }`
);
if (process.env.NAVIS_TV_PASSWORD) {
  console.log("[build:android] password    : baked into the APK");
}

const gradle = spawnSync(path.join(androidDir, "gradlew"), [gradleTask, "--console=plain"], {
  cwd: androidDir,
  stdio: "inherit",
  env: { ...process.env, JAVA_HOME: javaHome },
});

if (gradle.status !== 0) {
  fail("Gradle build failed.");
}

const apkDir = path.join(androidDir, "app", "build", "outputs", "apk", variant);
const apk = fs.existsSync(apkDir)
  ? fs.readdirSync(apkDir).find((name) => name.endsWith(".apk"))
  : null;

if (!apk) {
  fail(`Gradle reported success but no APK was found in ${apkDir}`);
}

fs.mkdirSync(outputDir, { recursive: true });
const destination = path.join(outputDir, apk);
fs.copyFileSync(path.join(apkDir, apk), destination);

const sizeMb = (fs.statSync(destination).size / (1024 * 1024)).toFixed(1);
console.log(`\n[build:android] APK ready: ${path.relative(projectRoot, destination)} (${sizeMb} MB)`);
console.log(`[build:android] Install it with: adb install -r ${path.relative(projectRoot, destination)}`);
